### ISSUE TITLE
python module name should be changed to `bpylist2`

### ISSUE THREAD

**Issue by doronz88** [xa4a/bpylist2#11]
I know this project is basically an improved fork of `bpylist`, but no two "competing" packages should have the same module name. Also, since they both use the same module name and the versions may collide, it would be better to seperate the two packages farther.

btw, amazing work!

**Comment by RhetTbull** [comment]
I agree with your rationale but as a user of this package, I think renaming it now would break too many things that assume it's called `bpylist`.  I'm relatively new to python and this "feature" which allows packages to be published on PyPI that clobber each other's namespaces has bitten me more than once!

**Comment by doronz88** [comment]
In this case you can have several solutions possible:

* Use the `<=version` in your package requirements.
* Import using `import bpylist2 as byplist`
* Create a dummy `bpylist` module per project that just redirects the import to `bpylist2`.

Any of the following would be better for this same reason. Explicit is always better then implicit, and if this doesn't happen soon, it never will (more stuff will break).

**Comment by parabolala** [comment]
Thanks for the considerate report.
I agree that having the module name `bpylist2` not match the package name `bpylist` is slightly confusing and might occasionally be error-prone.

Few considerations from my side:
* This module is _intended_ as a drop-in replacement for the original one (agree, violates "explicit better than implicit"), but has its merits
* Exists under the assumption that the former one is not updated or released. If Marketcircle/bpylist maintainers would ever show up and incorporate their PRs (incl. from this repo), my work here would be complete and this one will not be needed at all.
* The legacy of where this module is at ATM (i.e. used in a few places and I'm not actively working on it).

Overall, I'm open to renaming the module and releasing it as a new major package version. I will unlikely be working on this in the nearest future for personal reasons but will be happy to review/accept PRs.

**Comment by matan1008** [comment]
As a user of this package, I also had to deal with this issue.
In my humble opinion, converting it to `import bpylist2` is the best option.

**Comment by parabolala** [comment]
Thanks all for the input. 

I pushed https://github.com/parabolala/bpylist2/commit/314d8e8ecc4ea1161d0425ffbcb87764c429f3fc that renames the module to `bpylist2` and it's now published as [bpylist2==4.0.1](https://pypi.org/project/bpylist2/4.0.1/)
