### ISSUE TITLE
Pinned pycodestyle dependency conflicts with current flake8 requirements.

### ISSUE THREAD

**Issue by TheGS** [xa4a/bpylist2#6]
In the setup.py file, in the `setup_requires` parameter, the line `"pycodestyle==2.3.1"` causes a conflict with the current requirements for flake8, which are...
```
install_requires=
# We document the reasoning for using ranges here:
# http://flake8.pycqa.org/en/latest/faq.html#why-does-flake8-use-ranges-for-its-dependencies
# And in which releases we will update those ranges here:
# http://flake8.pycqa.org/en/latest/internal/releases.html#releasing-flake8
    pyflakes >= 2.1.0, < 2.2.0
    pycodestyle >= 2.5.0, < 2.6.0
    mccabe >= 0.6.0, < 0.7.0
    enum34; python_version<"3.4"
    typing; python_version<"3.5"
    configparser; python_version<"3.2"
    functools32; python_version<"3.2"
    importlib-metadata; python_version<"3.8"
```

**Comment by parabolala** [comment]
Thanks for the report. I'll take a look at this over weekend and will push and updated version with appropriately pinned versions.

**Comment by TheGS** [comment]
I would suggest that if you’re not using anything in pycodestyle yourself, to just remove that explicit requirement and let flake8 import what it needs as an internal dependency

**Comment by parabolala** [comment]
Done. Check the latest version 3.0.1
